version: '3.1'

services:

  drupal:
    image: drupal:8.2
    ports:
     - '8080:80'
    volumes: 
     - /var/www/html/modules
     - /var/www/html/profiles
     - /var/www/html/themes
     - /var/www/html/sites
    restart: always 


  postgres:
    image: postgres:latest
    secrets:
     - psql_pass
    environment: 
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_user
    restart: always 

  
secrets:
  psql_pass: 
    external: true 
    


